on:
  push:
    branches:
      - master
    tags:
      - "v*"

name: Build and push Docker to DockerHub

env:
  PROJECT_NAME: ${GITHUB_REPOSITORY#"$GITHUB_REPOSITORY_OWNER"/}
  APP_NAME: "${PROJECT_NAME%-docker}"
  APP_VERSION: ${GITHUB_REF#"/refs/tags/"}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Print variables
        run: echo "$GITHUB_REPOSITORY_OWNER $APP_NAME $APP_VERSION"
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     push: true
      #     tags: ${GITHUB_REPOSITORY_OWNER}/${APP_NAME}:latest,${GITHUB_REPOSITORY_OWNER}/${APP_NAME}:${APP_VERSION}
