on:
  push:
    branches:
      - master
    tags:
      - "v*"

name: Build and push Docker to DockerHub

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Get the version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.NAME }}:latest,${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.NAME }}:${GITHUB_REF/refs\/tags\//}
