on:
  push:
    # branches:
    #   - master
    tags:
      - "v*"

name: Build and push Docker to DockerHub

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set env PROJECT_NAME
        run: echo "PROJECT_NAME=${GITHUB_REPOSITORY#"$GITHUB_REPOSITORY_OWNER"/}" >> $GITHUB_ENV
      - name: Set env APP_NAME
        run: echo "APP_NAME=${PROJECT_NAME%-docker}" >> $GITHUB_ENV
      - name: Set env APP_VERSION
        run: echo "APP_VERSION=${GITHUB_REF#\/refs\/tags\/}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ github.repository_owner }}/${{ env.APP_NAME }}:latest,${{ github.repository_owner }}/${{ env.APP_NAME }}:${{ env.APP_VERSION }}
